
package student.hostel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.List;



public class AdminMenu extends javax.swing.JFrame {
    
    private ApplicationFormManager appmanager;

    
    public AdminMenu() {
        initComponents();
        appmanager = new ApplicationFormManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        HostelRoom = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        HostelRoomTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        studenthostel1 = new javax.swing.JTextField();
        studentname1 = new javax.swing.JTextField();
        studentid1 = new javax.swing.JTextField();
        update1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        studentnumber1 = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        all1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        payment1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        status1 = new javax.swing.JComboBox<>();
        roomtype1 = new javax.swing.JComboBox<>();
        HostelApps = new javax.swing.JPanel();
        studentroom2 = new javax.swing.JTextField();
        studentname2 = new javax.swing.JTextField();
        studentid2 = new javax.swing.JTextField();
        studentnumber2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        HostelAppTable2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        edit2 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        clear2 = new javax.swing.JButton();
        StudentRecs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentDataTable3 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        search3 = new javax.swing.JButton();
        studentid3 = new javax.swing.JTextField();
        studentname3 = new javax.swing.JTextField();
        studentnumber3 = new javax.swing.JTextField();
        clear3 = new javax.swing.JButton();
        Reports = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ReportsTable4 = new javax.swing.JTable();
        show4 = new javax.swing.JButton();
        clear4 = new javax.swing.JButton();
        try {
            chartPanel1 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "student/hostel/management/system.AdminMenu_chartPanel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        charts4 = new javax.swing.JButton();
        chartPanel2 = new javax.swing.JPanel();
        charts5 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        LoginInfo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        login5 = new javax.swing.JTextField();
        edit5 = new javax.swing.JButton();
        clear5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        password5 = new javax.swing.JTextField();
        add5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hostel Room Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hostel Applications");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Records");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reports");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login Information");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane2.setLayer(LoginInfo, JLayeredPane.MODAL_LAYER);

        HostelRoom.setBackground(new java.awt.Color(204, 204, 255));
        HostelRoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        roomtype1 = new JComboBox<>();
        roomtype1.addItem("Master Room");
        roomtype1.addItem("Medium Room");
        roomtype1.addItem("Small Room");
        roomtype1.addItem("2 Person Shared Room");
        roomtype1.addItem("4 Person Shared Room");

        roomtype1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedOption = roomtype1.getSelectedItem().toString();
                String paymentText = "";

                if (selectedOption.equals("Master Room")) {
                    paymentText = "RM 1100";
                } else if (selectedOption.equals("Medium Room")) {
                    paymentText = "RM 900";
                } else if (selectedOption.equals("Small Room")) {
                    paymentText = "RM 800";
                } else if (selectedOption.equals("2 Person Shared Room")) {
                    paymentText = "RM 600";
                } else if (selectedOption.equals("4 Person Shared Room")) {
                    paymentText = "RM 300";
                }

                payment1.setText(paymentText);
            }
        });

        HostelRoomTable1.setBackground(new java.awt.Color(255, 255, 255));
        HostelRoomTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(HostelRoomTable1);

        HostelRoom.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 630, 100));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Student Name:");
        HostelRoom.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Hostel Room:");
        HostelRoom.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Student ID:");
        HostelRoom.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Hostel Room Database");
        HostelRoom.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        studenthostel1.setBackground(new java.awt.Color(255, 255, 255));
        studenthostel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studenthostel1.setForeground(new java.awt.Color(0, 0, 0));
        HostelRoom.add(studenthostel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 270, -1));

        studentname1.setBackground(new java.awt.Color(255, 255, 255));
        studentname1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentname1.setForeground(new java.awt.Color(0, 0, 0));
        HostelRoom.add(studentname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 270, -1));

        studentid1.setBackground(new java.awt.Color(255, 255, 255));
        studentid1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentid1.setForeground(new java.awt.Color(0, 0, 0));
        studentid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentid1ActionPerformed(evt);
            }
        });
        HostelRoom.add(studentid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 270, -1));

        update1.setBackground(new java.awt.Color(255, 255, 255));
        update1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        update1.setForeground(new java.awt.Color(0, 0, 0));
        update1.setText("UPDATE");
        update1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        HostelRoom.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 60, 60));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Phone Number:");
        HostelRoom.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        studentnumber1.setBackground(new java.awt.Color(255, 255, 255));
        studentnumber1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentnumber1.setForeground(new java.awt.Color(0, 0, 0));
        HostelRoom.add(studentnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 270, -1));

        add1.setBackground(new java.awt.Color(255, 255, 255));
        add1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 0, 0));
        add1.setText("ADD");
        add1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        HostelRoom.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 60, 60));

        clear1.setBackground(new java.awt.Color(255, 255, 255));
        clear1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        clear1.setForeground(new java.awt.Color(0, 0, 0));
        clear1.setText("CLEAR");
        clear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        HostelRoom.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 130, 50));

        delete1.setBackground(new java.awt.Color(255, 255, 255));
        delete1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        delete1.setForeground(new java.awt.Color(0, 0, 0));
        delete1.setText("DELETE");
        delete1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        HostelRoom.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 60, 60));

        view1.setBackground(new java.awt.Color(255, 255, 255));
        view1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        view1.setForeground(new java.awt.Color(0, 0, 0));
        view1.setText("VIEW");
        view1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        HostelRoom.add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 60, 60));

        all1.setBackground(new java.awt.Color(255, 255, 255));
        all1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        all1.setForeground(new java.awt.Color(0, 0, 0));
        all1.setText("SHOW ALL");
        all1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        all1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all1ActionPerformed(evt);
            }
        });
        HostelRoom.add(all1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 130, 50));

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Status:");
        HostelRoom.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel32.setBackground(new java.awt.Color(0, 0, 0));
        jLabel32.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Payment:");
        HostelRoom.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        payment1.setBackground(new java.awt.Color(255, 255, 255));
        payment1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        payment1.setForeground(new java.awt.Color(0, 0, 0));
        HostelRoom.add(payment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 270, -1));

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Room Type:");
        HostelRoom.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        status1.setBackground(new java.awt.Color(255, 255, 255));
        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Paid" }));
        HostelRoom.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 270, -1));

        roomtype1.setBackground(new java.awt.Color(255, 255, 255));
        roomtype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master Room", "Medium Room", "Small Room", "2 Person Shared Room", "4 Person Shared Room" }));
        roomtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtype1ActionPerformed(evt);
            }
        });
        roomtype1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomtype1KeyPressed(evt);
            }
        });
        HostelRoom.add(roomtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, -1));

        HostelApps.setBackground(new java.awt.Color(204, 204, 255));
        HostelApps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentroom2.setBackground(new java.awt.Color(255, 255, 255));
        studentroom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentroom2ActionPerformed(evt);
            }
        });
        HostelApps.add(studentroom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 335, -1));

        studentname2.setBackground(new java.awt.Color(255, 255, 255));
        studentname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentname2ActionPerformed(evt);
            }
        });
        HostelApps.add(studentname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 335, -1));

        studentid2.setBackground(new java.awt.Color(255, 255, 255));
        studentid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentid2ActionPerformed(evt);
            }
        });
        HostelApps.add(studentid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 335, -1));

        studentnumber2.setBackground(new java.awt.Color(255, 255, 255));
        studentnumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnumber2ActionPerformed(evt);
            }
        });
        HostelApps.add(studentnumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 335, -1));

        HostelAppTable2.setBackground(new java.awt.Color(255, 255, 255));
        HostelAppTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Hostel Room"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(HostelAppTable2);

        HostelApps.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 530, 100));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Student Name:");
        HostelApps.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Hostel Room:");
        HostelApps.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Student ID:");
        HostelApps.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Phone Number:");
        HostelApps.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Hostel Applications");
        HostelApps.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        edit2.setBackground(new java.awt.Color(255, 255, 255));
        edit2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        edit2.setForeground(new java.awt.Color(0, 0, 0));
        edit2.setText("EDIT");
        edit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        HostelApps.add(edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 80, 20));

        submit2.setBackground(new java.awt.Color(255, 255, 255));
        submit2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        submit2.setForeground(new java.awt.Color(0, 0, 0));
        submit2.setText("SUBMIT");
        submit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        HostelApps.add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 80, 20));

        clear2.setBackground(new java.awt.Color(255, 255, 255));
        clear2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        clear2.setForeground(new java.awt.Color(0, 0, 0));
        clear2.setText("CLEAR");
        clear2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });
        HostelApps.add(clear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 80, 20));

        StudentRecs.setBackground(new java.awt.Color(204, 204, 255));

        StudentDataTable3.setBackground(new java.awt.Color(255, 255, 255));
        StudentDataTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Student ID", "Gender", "Address", "Phone Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentDataTable3);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Student Name:");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Phone Number:");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Student ID:");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Student Database");

        search3.setBackground(new java.awt.Color(255, 255, 255));
        search3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        search3.setForeground(new java.awt.Color(0, 0, 0));
        search3.setText("SEARCH");
        search3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });

        studentid3.setBackground(new java.awt.Color(255, 255, 255));
        studentid3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentid3.setForeground(new java.awt.Color(0, 0, 0));

        studentname3.setBackground(new java.awt.Color(255, 255, 255));
        studentname3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentname3.setForeground(new java.awt.Color(0, 0, 0));

        studentnumber3.setBackground(new java.awt.Color(255, 255, 255));
        studentnumber3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        studentnumber3.setForeground(new java.awt.Color(0, 0, 0));
        studentnumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnumber3ActionPerformed(evt);
            }
        });

        clear3.setBackground(new java.awt.Color(255, 255, 255));
        clear3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        clear3.setForeground(new java.awt.Color(0, 0, 0));
        clear3.setText("CLEAR");
        clear3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentRecsLayout = new javax.swing.GroupLayout(StudentRecs);
        StudentRecs.setLayout(StudentRecsLayout);
        StudentRecsLayout.setHorizontalGroup(
            StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentRecsLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRecsLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRecsLayout.createSequentialGroup()
                        .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentRecsLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(44, 44, 44)
                                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentid3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(StudentRecsLayout.createSequentialGroup()
                                        .addComponent(search3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(studentname3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        StudentRecsLayout.setVerticalGroup(
            StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRecsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(55, 55, 55)
                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(studentid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(studentname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(studentnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(StudentRecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search3)
                    .addComponent(clear3))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Reports.setBackground(new java.awt.Color(204, 204, 255));

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Reports");

        ReportsTable4.setBackground(new java.awt.Color(255, 255, 255));
        ReportsTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. of Students", "Paid Fees", "Unpaid Fees", "Rooms Available", "Monthly Income"
            }
        ));
        jScrollPane4.setViewportView(ReportsTable4);

        show4.setBackground(new java.awt.Color(255, 255, 255));
        show4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        show4.setForeground(new java.awt.Color(0, 0, 0));
        show4.setText("SHOW");
        show4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show4ActionPerformed(evt);
            }
        });

        clear4.setBackground(new java.awt.Color(255, 255, 255));
        clear4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        clear4.setForeground(new java.awt.Color(0, 0, 0));
        clear4.setText("CLEAR");
        clear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartPanel1Layout = new javax.swing.GroupLayout(chartPanel1);
        chartPanel1.setLayout(chartPanel1Layout);
        chartPanel1Layout.setHorizontalGroup(
            chartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        chartPanel1Layout.setVerticalGroup(
            chartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        charts4.setBackground(new java.awt.Color(255, 255, 255));
        charts4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        charts4.setForeground(new java.awt.Color(0, 0, 0));
        charts4.setText("Paid/Unpaid Chart");
        charts4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charts4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartPanel2Layout = new javax.swing.GroupLayout(chartPanel2);
        chartPanel2.setLayout(chartPanel2Layout);
        chartPanel2Layout.setHorizontalGroup(
            chartPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartPanel2Layout.setVerticalGroup(
            chartPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        charts5.setBackground(new java.awt.Color(255, 255, 255));
        charts5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        charts5.setForeground(new java.awt.Color(0, 0, 0));
        charts5.setText("Rooms Available/Not");
        charts5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charts5ActionPerformed(evt);
            }
        });

        label1.setText("Rooms Available - Green");

        label2.setText("Rooms Not Available - Red");

        label3.setText("Paid - Green");

        label4.setText("Unpaid - Red");

        javax.swing.GroupLayout ReportsLayout = new javax.swing.GroupLayout(Reports);
        Reports.setLayout(ReportsLayout);
        ReportsLayout.setHorizontalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(charts4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chartPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chartPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(charts5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                        .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(ReportsLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReportsLayout.setVerticalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsLayout.createSequentialGroup()
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                        .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chartPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chartPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charts4)
                            .addComponent(charts5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear4)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        LoginInfo.setBackground(new java.awt.Color(204, 204, 255));
        LoginInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Login Information");
        LoginInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Login ID:");
        LoginInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        login5.setBackground(new java.awt.Color(255, 255, 255));
        login5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        login5.setForeground(new java.awt.Color(0, 0, 0));
        LoginInfo.add(login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 300, -1));

        edit5.setBackground(new java.awt.Color(255, 255, 255));
        edit5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        edit5.setForeground(new java.awt.Color(0, 0, 0));
        edit5.setText("EDIT");
        edit5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit5ActionPerformed(evt);
            }
        });
        LoginInfo.add(edit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, -1));

        clear5.setBackground(new java.awt.Color(255, 255, 255));
        clear5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        clear5.setForeground(new java.awt.Color(0, 0, 0));
        clear5.setText("CLEAR");
        clear5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear5ActionPerformed(evt);
            }
        });
        LoginInfo.add(clear5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 120, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Password:");
        LoginInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        password5.setBackground(new java.awt.Color(255, 255, 255));
        password5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        password5.setForeground(new java.awt.Color(0, 0, 0));
        LoginInfo.add(password5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 300, -1));

        add5.setBackground(new java.awt.Color(255, 255, 255));
        add5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        add5.setForeground(new java.awt.Color(0, 0, 0));
        add5.setText("ADD");
        add5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add5ActionPerformed(evt);
            }
        });
        LoginInfo.add(add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        jLayeredPane2.setLayer(HostelRoom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(HostelApps, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(StudentRecs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Reports, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(LoginInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HostelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(HostelApps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(LoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(StudentRecs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(HostelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HostelApps, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(StudentRecs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 6, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Student Hostel Management System");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel2.setText("Hello, Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        HostelApps.setVisible(true);
        HostelRoom.setVisible(false);
        StudentRecs.setVisible(false);
        Reports.setVisible(false);
        LoginInfo.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void studentroom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentroom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentroom2ActionPerformed

    private void studentname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentname2ActionPerformed

    private void studentid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentid2ActionPerformed

    private void studentnumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnumber2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        StudentRecs.setVisible(true);
        HostelRoom.setVisible(false);
        Reports.setVisible(false);
        HostelApps.setVisible(false);
        LoginInfo.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        Reports.setVisible(true);
        HostelRoom.setVisible(false);
        StudentRecs.setVisible(false);
        HostelApps.setVisible(false);
        LoginInfo.setVisible(false);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        LoginInfo.setVisible(true);
        HostelApps.setVisible(false);
        StudentRecs.setVisible(false);
        Reports.setVisible(false);
        HostelRoom.setVisible(false);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        HostelRoom.setVisible(true);
        HostelApps.setVisible(false);
        StudentRecs.setVisible(false);
        Reports.setVisible(false);
        LoginInfo.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed
        String searchName = studentname3.getText().trim();
        String searchValue = studentid3.getText().trim();
        String searchPhoneNumber = studentnumber3.getText().trim();
        DefaultTableModel model = (DefaultTableModel) StudentDataTable3.getModel();
        model.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader("Student.txt"))) {
            String[] columnNames = {"Name", "Student ID", "Gender", "Address", "Phone Number", "Email"};
            model.setColumnIdentifiers(columnNames);

            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");

                if (data.length == 6) {
                    String studentName = data[0].trim();
                    String studentId = data[1].trim();
                    String gender = data[2].trim();
                    String address = data[3].trim();
                    String phoneNumber = data[4].trim();
                    String email = data[5].trim();

                    if (studentId.equals(searchValue) || studentName.equalsIgnoreCase(searchName) || phoneNumber.equals(searchPhoneNumber)) {
                        model.addRow(new Object[]{studentName, studentId, gender, address, phoneNumber, email});
                    }
                }
            }
        } catch (IOException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }//GEN-LAST:event_search3ActionPerformed

    private void clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ActionPerformed
        studentid3.setText("");
        studentname3.setText("");
        studentnumber3.setText("");
        
        DefaultTableModel model = (DefaultTableModel) StudentDataTable3.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear3ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        String update_id =  studentid2.getText().trim();
        String update_name =  studentname2.getText().trim();
        String update_number =  studentnumber2.getText().trim();
        String update_hostel =  studentroom2.getText().trim();
        
        HostelApplications formappManager = new HostelApplications();
        formappManager.updateRegistrationData(update_id, update_name, update_number, update_hostel);
    }//GEN-LAST:event_edit2ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        
        String searchStudentId = studentid2.getText().trim();
        
        String filePath = "HostelForms.txt";
        File file = new File(filePath);
        
        
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            br.readLine();
            String[] columnNames = {"Student ID", "Name", "Phone Number", "Hostel Room"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                String studentId = data[0].trim();
                String name = data[1].trim();
                String phoneNumber = data[2].trim();
                String hostelRoom = data[3].trim();
                if (studentId.equals(searchStudentId)) {
                    model.addRow(new Object[]{studentId, name, phoneNumber, hostelRoom});
                }
            }
            HostelAppTable2.setModel(model);
        } catch (IOException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }//GEN-LAST:event_submit2ActionPerformed

    private void studentid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentid1ActionPerformed
        
    }//GEN-LAST:event_studentid1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        if (studentid1.getText().isEmpty() || studentname1.getText().isEmpty() || studentnumber1.getText().isEmpty() || studenthostel1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill all of the fields! ");
        }
        else
        {
            String input_id =  studentid1.getText().trim();
            String input_name =  studentname1.getText().trim();
            String input_number =  studentnumber1.getText().trim();
            String input_hostel =  studenthostel1.getText().trim();
            String input_room = roomtype1.getSelectedItem().toString();
            String input_pay = payment1.getText().trim();
            String input_status = status1.getSelectedItem().toString();
            
            ApplicationFormManager formManager = new ApplicationFormManager();
            formManager.addRegistrationData(input_id, input_name, input_number, input_hostel, input_room, input_pay, input_status);
            
        }
        
    }//GEN-LAST:event_add1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String edit_id =  studentid1.getText().trim();
        String edit_name =  studentname1.getText().trim();
        String edit_number =  studentnumber1.getText().trim();
        String edit_hostel =  studenthostel1.getText().trim();
        String edit_room = roomtype1.getSelectedItem().toString();
        String edit_pay = payment1.getText().trim();
        String edit_status = status1.getSelectedItem().toString();
        
        ApplicationFormManager formManager = new ApplicationFormManager();
        formManager.editRegistrationData(edit_id, edit_name, edit_number, edit_hostel, edit_room, edit_pay, edit_status);
    }//GEN-LAST:event_update1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        String delete_id =  studentid1.getText().trim();
        String delete_name =  studentname1.getText().trim();
        String delete_number =  studentnumber1.getText().trim();
        String delete_hostel =  studenthostel1.getText().trim();
        String delete_room = roomtype1.getSelectedItem().toString();
        String delete_pay = payment1.getText().trim();
        String delete_status = status1.getSelectedItem().toString();
        
        ApplicationFormManager formManager = new ApplicationFormManager();
        formManager.deleteRegistrationData(delete_id, delete_name, delete_number, delete_hostel,delete_room, delete_pay, delete_status);
    }//GEN-LAST:event_delete1ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        studentid1.setText("");
        studentname1.setText("");
        studentnumber1.setText("");
        studenthostel1.setText("");
        roomtype1.setSelectedIndex(0);
        payment1.setText("");
        status1.setSelectedIndex(0);
        
        DefaultTableModel model = (DefaultTableModel) HostelRoomTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear1ActionPerformed

    private void all1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all1ActionPerformed
        String filePath = "HostelApplications.txt";
        File file = new File(filePath);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String[] columnNames = {"Student ID", "Name", "Phone Number", "Hostel Room", "Room Type", "Payment", "Status"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            String line;
            while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    
                    String studentId = data[0];
                    
                    String name = data[1];
                    String phoneNumber = data[2];
                    String hostelRoom = data[3];
                    String roomType = data[4];
                    String payment = data[5];
                    String status = data[6];
                    
                    model.addRow(new Object[]{studentId, name, phoneNumber, hostelRoom, roomType, payment, status});
                    
                    br.readLine();
            }

            HostelRoomTable1.setModel(model);
        } catch (IOException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }//GEN-LAST:event_all1ActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        String searchStudentId = studentid1.getText().trim();

        String filePath = "HostelApplications.txt";
        File file = new File(filePath);

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String[] columnNames = {"Student ID", "Name", "Phone Number", "Hostel Room", "Room Type", "Payment", "Status"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            String line;
            while ((line = br.readLine()) != null) {
                    
                    String[] data = line.split(",");
                    
                    String studentId = data[0];
                    String name = data[1];
                    String phoneNumber = data[2];
                    String hostelRoom = data[3];
                    String roomType = data[4];
                    String payment = data[5];
                    String status = data[6];
                    
                    if (studentId.equals(searchStudentId)) {
                        model.addRow(new Object[]{studentId, name, phoneNumber, hostelRoom, roomType, payment, status});
                    }
            }

            HostelRoomTable1.setModel(model);
        } catch (IOException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }//GEN-LAST:event_view1ActionPerformed

    private void roomtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtype1ActionPerformed
        JComboBox<String> roomtype1 = new JComboBox<>();
        JTextField payment1 = new JTextField();


        roomtype1.addItem("Master Room");
        roomtype1.addItem("Medium Room");
        roomtype1.addItem("Small Room");
        roomtype1.addItem("2 Person Shared Room");
        roomtype1.addItem("4 Person Shared Room");

        roomtype1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedOption = roomtype1.getSelectedItem().toString();
                String paymentText = "";

                if (selectedOption.equals("Master Room")) {
                    paymentText = "RM 1100";
                } else if (selectedOption.equals("Medium Room")) {
                    paymentText = "RM 900";
                } else if (selectedOption.equals("Small Room")) {
                    paymentText = "RM 800";
                } else if (selectedOption.equals("2 Person Shared Room")) {
                    paymentText = "RM 600";
                } else if (selectedOption.equals("4 Person Shared Room")) {
                    paymentText = "RM 300";
                }

                payment1.setText(paymentText);
            }
        });
    }//GEN-LAST:event_roomtype1ActionPerformed

    private void roomtype1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomtype1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomtype1KeyPressed

    private void studentnumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnumber3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnumber3ActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        studentid2.setText("");
        studentname2.setText("");
        studentnumber2.setText("");
        studentroom2.setText("");
        
        DefaultTableModel model = (DefaultTableModel) HostelAppTable2.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear2ActionPerformed

    private void show4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show4ActionPerformed
        Records records = new Records();
        records.calculateInformation();
        
        int numberOfStudents = records.getNumberOfStudents();
        int paidFees = records.getPaidFees();
        int unpaidFees = records.getUnpaidFees();
        int roomsAvailable = records.getRoomsAvailable();
        int monthlyIncome = records.getMonthlyIncome();
        
        String[] columnNames = {"No. of Students","Paid Fees", "Unpaid Fees", "Rooms Available", "Monthly Income"};
        Object[][] data = {
            {records.getNumberOfStudents(), records.getPaidFees(), records.getUnpaidFees(), records.getRoomsAvailable(), records.getMonthlyIncome()}
        };
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        
        ReportsTable4.setModel(model);
    }//GEN-LAST:event_show4ActionPerformed

    private void clear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) ReportsTable4.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clear4ActionPerformed

    private void charts4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charts4ActionPerformed
        Records records = new Records();
        records.calculateInformation();

        PieChart pieChart = new PieChart(records.getPaidFees(), records.getUnpaidFees());

        chartPanel1.removeAll();
        chartPanel1.setLayout(new BorderLayout());
        chartPanel1.add(pieChart, BorderLayout.CENTER);
        chartPanel1.revalidate();
        chartPanel1.repaint();
        
        chartPanel1.setVisible(true);
    }//GEN-LAST:event_charts4ActionPerformed

    private void charts5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charts5ActionPerformed
        Records records = new Records();
        records.calculateInformation();
        PieChart2 pieChart2 = new PieChart2(records.getRoomsAvailable());

        chartPanel2.removeAll();
        chartPanel2.setLayout(new BorderLayout());
        chartPanel2.add(pieChart2, BorderLayout.CENTER);
        chartPanel2.revalidate();
        chartPanel2.repaint();
        
        chartPanel2.setVisible(true);
    }//GEN-LAST:event_charts5ActionPerformed

    private void edit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit5ActionPerformed
        LoginFileManager loginfm = new LoginFileManager();        String loginId = login5.getText();
        String newPassword = password5.getText();
        loginfm.editLogin(loginId, newPassword);
    }//GEN-LAST:event_edit5ActionPerformed

    private void clear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear5ActionPerformed
        login5.setText("");
        password5.setText("");
    }//GEN-LAST:event_clear5ActionPerformed

    private void add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add5ActionPerformed
        String loginId = login5.getText();
        String password = password5.getText();
        LoginFileManager.addLogin(loginId, password);
    }//GEN-LAST:event_add5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HostelAppTable2;
    private javax.swing.JPanel HostelApps;
    private javax.swing.JPanel HostelRoom;
    private javax.swing.JTable HostelRoomTable1;
    private javax.swing.JPanel LoginInfo;
    private javax.swing.JPanel Reports;
    private javax.swing.JTable ReportsTable4;
    private javax.swing.JTable StudentDataTable3;
    private javax.swing.JPanel StudentRecs;
    private javax.swing.JButton add1;
    private javax.swing.JButton add5;
    private javax.swing.JButton all1;
    private javax.swing.JPanel chartPanel1;
    private javax.swing.JPanel chartPanel2;
    private javax.swing.JButton charts4;
    private javax.swing.JButton charts5;
    private javax.swing.JButton clear1;
    private javax.swing.JButton clear2;
    private javax.swing.JButton clear3;
    private javax.swing.JButton clear4;
    private javax.swing.JButton clear5;
    private javax.swing.JButton delete1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextField login5;
    private javax.swing.JTextField password5;
    private javax.swing.JTextField payment1;
    private javax.swing.JComboBox<String> roomtype1;
    private javax.swing.JButton search3;
    private javax.swing.JButton show4;
    private javax.swing.JComboBox<String> status1;
    private javax.swing.JTextField studenthostel1;
    private javax.swing.JTextField studentid1;
    private javax.swing.JTextField studentid2;
    private javax.swing.JTextField studentid3;
    private javax.swing.JTextField studentname1;
    private javax.swing.JTextField studentname2;
    private javax.swing.JTextField studentname3;
    private javax.swing.JTextField studentnumber1;
    private javax.swing.JTextField studentnumber2;
    private javax.swing.JTextField studentnumber3;
    private javax.swing.JTextField studentroom2;
    private javax.swing.JButton submit2;
    private javax.swing.JButton update1;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables
}

